### ISSUE TITLE
Gtk.IconTheme.get_default() is null

### ISSUE THREAD

**Issue by ghost** [pepe386/fedora-update#1]
Hi,
Congratulations on working on this extension.
I installed it from the Gnome Extensions website and it worked right away. When I leave the session or restart the extension does not work and the Gnome Extensions app reports the following error: "Gtk.IconTheme.get_default() is null".
Uninstalling it works during the session. On the next session this error returns.
Use updated Fedora 34.

**Comment by travislankow** [comment]
Believe I have resolved, and opened PR #2 to merge. :)

**Comment by pepe386** [comment]
I will close the issue as I believe it was fixed with the merged PR #2 . Thanks @travislankow
